baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: JIG
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Blog
          url: https://blog.jigomezit.com
          weight: 30
        - name: Resume
          url: https://resume.jigomezit.com
          weight: 30
        #- name: Projects
        #  url: 
        #  weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Juan Ignacio Gomez
    description: Hi, I'm Juan Ignacio and this is my website!

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Juan Ignacio Gomez
        description: |

    
           I am a Cloud Engineer. 
        

          
        imageUrl: "/images/profile.png"
        imageTitle: my image
        imageWidth: 350
        imageHeight: 350
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/jigomezit/"
        - name: github
          url: "https://github.com/jigomezit"
        - name: twitter
          url: "https://www.twitter.com/jigomezit/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

